[[main]]
identifier = "about"
name = "About"
url = "/about"
[main.params]
icon = "user"

[[main]]
identifier = "links"
name = "Links"
url = "/links"
[main.params]
icon = "link"

[[main]]
identifier = "tags"
name = "Tags"
url = "/all-tags/"
[main.params]
icon = "tag"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/MyLoveES"

[social.params]
icon = "brand-github"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"