[[main]]
identifier = "archives"
name = "Archives"
url = "/archives"
[main.params]
icon = "archives"
weight = 4

[[main]]
identifier = "categories"
name = "Categories"
[main.params]
icon = "categories"
weight = 5

[[main]]
identifier = "tags"
name = "Tags"
url = "/all-tags"
[main.params]
icon = "tag"
weight = 6

[[main]]
identifier = "about"
name = "About"
url = "/about"
[main.params]
icon = "user"
weight = 10

[[main]]
identifier = "links"
name = "Links"
url = "/links"
[main.params]
icon = "link"
weight = 7

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/MyLoveES"
[social.params]
icon = "brand-github"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
[social.params]
icon = "rss"